### ISSUE TITLE
Emojis in a collapsable section are not parsed properly

### ISSUE THREAD

**Issue by mario-fazli** [yuin/goldmark-emoji#6]
Version: latest
Emojis in a collapsable section are not parsed in the html:

This is collapsable section from md:
```
## Collapsable section

<details>
  <summary>Emojis</summary>
  Lets try emoji :v:
</details>
```

The expected result is ```:v:``` to be parsed as ✌️ , but instead it stays as ```:v:```

**Comment by yuin** [comment]
Works as expected.
You should read CommonMark spec about HTML Blocks.

https://spec.commonmark.org/0.30/#html-blocks
